name: Build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build Rust Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cargo Build
        run: cargo build --verbose

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
